### ISSUE TITLE
既然叫 Plugin-Locale-Kotlin 有计划支持 kotlin 的桌面平台吗？

### ISSUE THREAD

**Issue by gtf35** [RebornQ/MultiLanguagesDemo-Kotlin#10]
名字是 Plugin-Locale-Kotlin，目标是不是只要是 kotlin 能运行的平台都支持？
有计划支持桌面平台吗？

**Comment by RebornQ** [comment]
> 名字是 Plugin-Locale-Kotlin，目标是不是只要是 kotlin 能运行的平台都支持？
> 有计划支持桌面平台吗？

@gtf35 没有试过 Kotlin 的桌面开发，不知道支持率如何😂。理论上只支持 Android，因为里面很多生命周期的监听都是 Android 独有的（其实后来有想过改名的，不过有人已经用了就算了😂）

至于支持桌面平台的话暂时没有计划。太菜了，搞不来桌面开发（

**Comment by gtf35** [comment]
明白了 感谢
