### ISSUE TITLE
fragment 中的问题

### ISSUE THREAD

**Issue by ousq** [RebornQ/MultiLanguagesDemo-Kotlin#3]
我是五个fragement  第一次选择之后切换 正常  
当退出应用之后再  最后两个fragment 没有起作用

**Comment by ousq** [comment]
![image](https://user-images.githubusercontent.com/18591884/71965281-56902280-323a-11ea-8a71-2bac2a1cdf54.png)
然后自己在base 添加这个就可以了 暂时没有 发现问题

**Comment by RebornQ** [comment]
@ousq  咦？Fragment的不是跟随Activity的资源吗？讲道理不用再在Base那里Update一次的，我去看看
