### ISSUE TITLE
在9.0测试切换语言 关闭dialog 都要闪一下

### ISSUE THREAD

**Issue by ousq** [RebornQ/MultiLanguagesDemo-Kotlin#6]
用demo 运行一样的

**Comment by RebornQ** [comment]
啊？有动态图可以发一下吗？我这边没有这个问题噢，只有切换了语言的那一瞬间才会闪一下（必须闪的，因为要重建Activity），其他地方不会闪的

**Comment by RebornQ** [comment]
@ousq

**Comment by ousq** [comment]
是的就是这个原因

**Comment by ousq** [comment]
感觉还是系统吧 我用8.0的测试不会闪  然后在9.0上测试 就要闪一下

**Comment by ousq** [comment]
就是这种情况能解决嘛 就保留在当前的activity

**Comment by ousq** [comment]
后面我换成自定义刷新了 就可以了

**Comment by RebornQ** [comment]
@ousq 貌似没办法控制这个刷新动画，你说的自定义刷新是指自己实现刷新方式吗？

**Comment by ousq** [comment]
是的 我就自己手动改变当前界面的 上的内容 @RebornQ  还好不多

**Comment by RebornQ** [comment]
@ousq  方便问一下你是怎么实现的吗？我想参考一下能不能改一改让他不闪，不方便的话就算了，我自己研究研究哈哈哈～
