### ISSUE TITLE
切换语言重启的时候是否可以加入渐变效果

### ISSUE THREAD

**Issue by ydmmocoo** [RebornQ/MultiLanguagesDemo-Kotlin#7]
如题，加入渐变效果可以使切换看过去不那么突兀。具体可以参考下https://github.com/getActivity/MultiLanguages的切换效果

**Comment by RebornQ** [comment]
> 如题，加入渐变效果可以使切换看过去不那么突兀。具体可以参考下[https://github.com/getActivity/MultiLanguages的切换效果](https://github.com/getActivity/MultiLanguages%E7%9A%84%E5%88%87%E6%8D%A2%E6%95%88%E6%9E%9C)

@ydmmocoo 我其实在研究怎么让你们自定义切换效果😂️，晚点我看看
